name: Calculator CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Run JUnit tests
        #run: |
          #javac -cp junit-platform-console-standalone-1.8.2.jar:. Calculatrice/*.java CalculTest/*.java
          #java -jar junit-platform-console-standalone-1.8.2.jar --class-path . --scan-class-path

